services:
  immudb:
    image: codenotary/immudb:1.9
    platform: linux/amd64
    ports:
      - 3322:3322 # immudb gRPC server
      - 8080:8080 # immudb Web Console
    depends_on:
      - minio
    environment:
      IMMUDB_ADDRESS: 0.0.0.0
      IMMUDB_PORT: 3322
      IMMUDB_USER: immudb
      IMMUDB_PWD: immudb
      IMMUDB_DBNAME: immudb
      IMMUDB_TOKENSIZE: 64
      IMMUDB_S3_ACCESS_KEY_ID: minio-user
      IMMUDB_S3_SECRET_KEY: minio-password
      IMMUDB_S3_STORAGE: true
      IMMUDB_S3_BUCKET_NAME: immudb-bucket
      IMMUDB_S3_PATH_PREFIX: immudb-prefix
      IMMUDB_S3_ENDPOINT: http://minio:9000
    networks:
      - minionetwork

  minio:
    image: minio/minio:RELEASE.2024-10-13T13-34-11Z
    ports:
      - '9000:9000' # MinIO API
      - '9001:9001' # MinIO Console
    networks:
      - minionetwork
    environment:
      MINIO_ROOT_USER: minio-user
      MINIO_ROOT_PASSWORD: minio-password
    command: server /data --console-address ":9001"

networks:
  minionetwork:
    driver: bridge
